csiConfig:
  - clusterID: c966095a-6e4e-11ef-82d6-0131360f7c6f
    monitors:
      - 172.18.15.101:6789
      - 172.18.15.102:6789
      - 172.18.15.103:6789

provisioner:
  tolerations:
    - operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerm:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
nodeplugin:
  tolerations:
    - operator: Exists
readAffinity:
  enabled: true